export const TOP_CRYPTOS = [
  { symbol: "BTC", name: "Bitcoin" },
  { symbol: "ETH", name: "Ethereum" },
  { symbol: "USDT", name: "Tether" },
  { symbol: "BNB", name: "Binance Coin" },
  { symbol: "SOL", name: "Solana" },
  { symbol: "USDC", name: "USD Coin" },
  { symbol: "XRP", name: "XRP" },
  { symbol: "DOGE", name: "Dogecoin" },
  { symbol: "TON", name: "Toncoin" },
  { symbol: "ADA", name: "Cardano" },
  { symbol: "SHIB", name: "Shiba Inu" },
  { symbol: "AVAX", name: "Avalanche" },
  { symbol: "WBTC", name: "Wrapped Bitcoin" },
  { symbol: "DOT", name: "Polkadot" },
  { symbol: "TRX", name: "TRON" },
  { symbol: "LINK", name: "Chainlink" },
  { symbol: "MATIC", name: "Polygon" },
  { symbol: "NEAR", name: "NEAR Protocol" },
  { symbol: "UNI", name: "Uniswap" },
  { symbol: "BCH", name: "Bitcoin Cash" },
  { symbol: "LTC", name: "Litecoin" },
  { symbol: "APT", name: "Aptos" },
  { symbol: "ATOM", name: "Cosmos" },
  { symbol: "FIL", name: "Filecoin" },
  { symbol: "XLM", name: "Stellar" },
  { symbol: "RNDR", name: "Render" },
  { symbol: "IMX", name: "Immutable" },
  { symbol: "HBAR", name: "Hedera" },
  { symbol: "ARB", name: "Arbitrum" },
  { symbol: "VET", name: "VeChain" },
  { symbol: "OP", name: "Optimism" },
  { symbol: "MNT", name: "Mantle" },
  { symbol: "XMR", name: "Monero" },
  { symbol: "KAS", name: "Kaspa" },
  { symbol: "STX", name: "Stacks" },
  { symbol: "TIA", name: "Celestia" },
  { symbol: "OKB", name: "OKB" },
  { symbol: "FDUSD", name: "First Digital USD" },
  { symbol: "CRO", name: "Cronos" },
  { symbol: "RUNE", name: "THORChain" },
  { symbol: "INJ", name: "Injective" },
  { symbol: "GRT", name: "The Graph" },
  { symbol: "TAO", name: "Bittensor" },
  { symbol: "PEPE", name: "Pepe" },
  { symbol: "SUI", name: "Sui" },
  { symbol: "LDO", name: "Lido DAO" },
  { symbol: "FLOKI", name: "FLOKI" },
  { symbol: "ALGO", name: "Algorand" },
  { symbol: "FLOW", name: "Flow" },
  { symbol: "SEI", name: "Sei" },
  { symbol: "THETA", name: "Theta Network" },
  { symbol: "FET", name: "Fetch.ai" },
  { symbol: "GALA", name: "Gala" },
  { symbol: "BEAM", name: "Beam" },
  { symbol: "JUP", name: "Jupiter" },
  { symbol: "AAVE", name: "Aave" },
  { symbol: "WIF", name: "dogwifhat" },
  { symbol: "BONK", name: "Bonk" },
  { symbol: "EGLD", name: "MultiversX" },
  { symbol: "SAND", name: "The Sandbox" },
  { symbol: "STRK", name: "Starknet" },
  { symbol: "AXS", name: "Axie Infinity" },
  { symbol: "EOS", name: "EOS" },
  { symbol: "XTZ", name: "Tezos" },
  { symbol: "KCS", name: "KuCoin Token" },
  { symbol: "BTT", name: "BitTorrent" },
  { symbol: "NEO", name: "Neo" },
  { symbol: "BSV", name: "Bitcoin SV" },
  { symbol: "USDD", name: "USDD" },
  { symbol: "MINA", name: "Mina" },
  { symbol: "CHZ", name: "Chiliz" },
  { symbol: "KAVA", name: "Kava" },
  { symbol: "DYDX", name: "dYdX" },
  { symbol: "WLD", name: "Worldcoin" },
  { symbol: "MANA", name: "Decentraland" },
  { symbol: "CFX", name: "Conflux" },
  { symbol: "ASTR", name: "Astar" },
  { symbol: "SNX", name: "Synthetix" },
  { symbol: "AKT", name: "Akash Network" },
  { symbol: "OCEAN", name: "Ocean Protocol" },
  { symbol: "HNT", name: "Helium" },
  { symbol: "PENDLE", name: "Pendle" },
  { symbol: "ZIL", name: "Zilliqa" },
  { symbol: "COMP", name: "Compound" },
  { symbol: "ROSE", name: "Oasis Network" },
  { symbol: "IOTA", name: "IOTA" },
  { symbol: "GNO", name: "Gnosis" },
  { symbol: "ONT", name: "Ontology" },
  { symbol: "AGIX", name: "SingularityNET" },
  { symbol: "APE", name: "ApeCoin" },
  { symbol: "GMT", name: "STEPN" },
  { symbol: "ZEC", name: "Zcash" },
  { symbol: "QNT", name: "Quant" },
  { symbol: "FTM", name: "Fantom" },
  { symbol: "CAKE", name: "PancakeSwap" },
  { symbol: "XEC", name: "eCash" },
  { symbol: "DASH", name: "Dash" },
  { symbol: "ENS", name: "Ethereum Name Service" },
  { symbol: "NEXO", name: "Nexo" },
  { symbol: "WOO", name: "WOO Network" },
  { symbol: "BAT", name: "Basic Attention Token" },
  { symbol: "1INCH", name: "1inch Network" },
] as const;
